version: '2'
services:
  mysql:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: "password"
        MYSQL_DATABASE: "monitor"
      ports:
        - 3306:3306
      restart: no
  monitor-server:
      build: .
      environment:
        SPRING_PROFILES_ACTIVE: aws-dev