version: '2'
services:

  monitor-server:
      image: polinchw/monitor-server:1.7.36
      environment:
        SPRING_PROFILES_ACTIVE: aws-dev
      stdin_open: true
      tty: true
      ports:
      - 8080:8080/tcp
      labels:
        io.rancher.container.pull_image: always