@startuml


package "AWS VPC" {
  folder "Non-Public Facing" {
    folder "Database Subnet" {
        [AWS RDS]  --> MySql
    }
    folder "App Server Subnet" {
        [Spring Boot]
    }
  }
  folder "Public Facing" {
    folder "Web Server Subnet" {

       [Angular 2] --> [Spring Boot]
    }
  }
}

cloud {
  [Rasberry PI]
}

[Rasberry PI] --> [Angular 2]

database "MySql" {

}


@enduml