FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD monitor-server.jar /opt/monitor-server/
EXPOSE 8080
WORKDIR /opt/monitor-server/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "monitor-server.jar"]
